# Generated by Django 5.1.1 on 2024-10-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Weight in kilograms')),
                ('height', models.FloatField(help_text='Height in centimeters')),
                ('waist_circumference', models.FloatField(help_text='Waist circumference in centimeters')),
                ('hip_circumference', models.FloatField(blank=True, help_text='Hip circumference in centimeters', null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('whr', models.FloatField(blank=True, null=True)),
                ('whtr', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
