# Generated by Django 5.1.1 on 2024-11-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietplan',
            name='suitable_age_group',
        ),
        migrations.RemoveField(
            model_name='userdietplan',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Gender suitability', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='max_bmi',
            field=models.FloatField(default='50', help_text='Maximum BMI for this diet plan'),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='min_bmi',
            field=models.FloatField(default='0', help_text='Minimum BMI for this diet plan'),
        ),
    ]
